trying to fix slack notifier

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -228,3 +228,94 @@ run-unittests-and-lint:
       else
         ./Tests/scripts/slack_notifier.sh 'unittests' ./env_results.json
       fi
+
+
+run-validations:
+  stage: unittests-and-validations
+  artifacts:
+    expire_in: 48 hrs
+    paths:
+      - /builds/xsoar/content/unit-tests
+      - /builds/xsoar/content/artifacts/*
+    when: always
+  script:
+    - echo "====Look For Secrets===="
+    - demisto-sdk secrets --post-commit --ignore-entropy
+    - echo "====Create id set===="
+    - demisto-sdk create-id-set -o ./Tests/id_set.json
+    - cp ./Tests/id_set.json $ARTIFACTS_FOLDER
+    - echo "====Merge public and private id sets"
+    - |
+      if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+          echo "Skipping, Should not run on contributor's branch."
+      else
+        GCS_PATH=$(mktemp)
+        echo "$GCS_MARKET_KEY" > "$GCS_PATH"
+        gcloud auth activate-service-account --key-file="$GCS_PATH" > auth.out 2>&1
+        echo "successfully activated google cloud service account"
+
+        echo "Download private ID set"
+        gsutil cp gs://marketplace-dist/content/private_id_set.json $ARTIFACTS_FOLDER/unified_id_set.json
+        echo "successfully downloaded private ID set"
+        gcloud auth revoke --all &> /dev/null
+        rm $GCS_PATH
+
+        echo "Merge public and private ID sets"
+        demisto-sdk merge-id-sets -i1 ./Tests/id_set.json -i2 $ARTIFACTS_FOLDER/unified_id_set.json -o $CIRCLE_ARTIFACTS/unified_id_set.json
+        echo "successfully merged public and private ID sets"
+      fi
+    - echo "====Update Tests===="
+    - python3 ./Tests/scripts/update_conf_json.py
+    - cp "./Tests/conf.json" "$ARTIFACTS_FOLDER/conf.json"
+    - echo "====Validate Files and Yaml===="
+    - |
+      if [[ "$(echo "$GCS_MARKET_BUCKET" | tr '[:upper:]' '[:lower:]')" != "marketplace-dist" ]]; then
+        echo "Skipping the -Validate Files and Yaml- step when uploading to a test bucket."
+      else
+        echo "Run flake8 on all excluding Packs (Integraions and Scripts) - they will be handled in linting"
+        ./Tests/scripts/pyflake.sh *.py
+        find . -maxdepth 1 -type d -not \( -path . -o -path ./Packs -o -path ./venv \) | xargs ./Tests/scripts/pyflake.sh
+        echo "Run validate"
+        ./Tests/scripts/validate.sh
+      fi
+    - echo "====Check Spelling===="
+    - python3 ./Tests/scripts/circleci_spell_checker.py $CI_COMMIT_BRANCH
+    - echo "====Check Build Files Are Up To Date===="
+    - |
+      if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+        echo "Skipping, Should not run on contributor's branch."
+      else
+        ./Tests/scripts/is_file_up_to_date.sh .gitlab-ci.yml
+        ./Tests/scripts/is_file_up_to_date.sh .dev-requirements-py2.txt
+        ./Tests/scripts/is_file_up_to_date.sh .dev-requirements-py3.txt
+      fi
+    - echo "====Validate content-test-conf Branch Merged"
+    - |
+      if [[ $CI_COMMIT_BRANCH = "master" ]]; then
+        echo "Skipping, Should not run on master branch."
+      else
+        # replace slashes ('/') in the branch name, if exist, with underscores ('_')
+        UNDERSCORE_CI_BRANCH=${CI_COMMIT_BRANCH//\//_}
+        wget --header "Accept: application/vnd.github.v3.raw" --header "Authorization: token $GITHUB_TOKEN" "https://github.com/demisto/content-test-conf/archive/$UNDERSCORE_CI_BRANCH.zip" --no-check-certificate -q
+        if [ "$?" != "0" ]; then
+          echo "No such branch in content-test-conf: $UNDERSCORE_CI_BRANCH"
+        else
+          echo "ERROR: Found a branch with the same name in contest-test-conf conf.json - $UNDERSCORE_CI_BRANCH.\n Merge it in order to merge the current branch into content repo."
+          exit 1
+        fi
+      fi
+    - echo "====Validate landingPageSections.json===="
+    - # Download index.zip
+    - INDEX_PATH=$(mktemp)
+    - gsutil cp gs://marketplace-dist/content/packs/index.zip $INDEX_PATH
+    - echo "successfully downloaded index.zip into $INDEX_PATH"
+
+    - UNZIP_PATH=$(mktemp -d)
+    - unzip $INDEX_PATH -d $UNZIP_PATH
+
+    - python3 Tests/Marketplace/validate_landing_page_sections.py -i $UNZIP_PATH
+    - echo "====Run Slack Notifier===="
+    - |
+      if [ -n "${BUCKET_UPLOAD}" ]; then
+        ./Tests/scripts/slack_notifier.sh 'bucket_upload_flow' '' "$SLACK_CHANNEL"
+      fi
