trying to make Validate content-test-conf Branch Merged happen

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -298,14 +298,14 @@ run-validations:
       else
         # replace slashes ('/') in the branch name, if exist, with underscores ('_')
         UNDERSCORE_CI_BRANCH=${CI_COMMIT_BRANCH//\//_}
-        wget --header "Accept: application/vnd.github.v3.raw" --header "Authorization: token $GITHUB_TOKEN" "https://github.com/demisto/content-test-conf/archive/$UNDERSCORE_CI_BRANCH.zip" --no-check-certificate
-        if [ "$?" != "0" ]; then
-          echo "No such branch in content-test-conf: $UNDERSCORE_CI_BRANCH"
-        else
-          echo "ERROR: Found a branch with the same name in contest-test-conf conf.json - $UNDERSCORE_CI_BRANCH.\n Merge it in order to merge the current branch into content repo."
-          exit 1
-        fi
-      fi
+        wget --header "Accept: application/vnd.github.v3.raw" --header "Authorization: token $GITHUB_TOKEN" "https://github.com/demisto/content-test-conf/archive/$UNDERSCORE_CI_BRANCH.zip" --no-check-certificate -q || {
+          if [ "$?" != "0" ]; then
+            echo "No such branch in content-test-conf: $UNDERSCORE_CI_BRANCH"
+          else
+            echo "ERROR: Found a branch with the same name in contest-test-conf conf.json - $UNDERSCORE_CI_BRANCH.\n Merge it in order to merge the current branch into content repo."
+            exit 1
+          fi
+        }
     - echo "====Validate landingPageSections.json===="
     - echo "Download index.zip"
     - INDEX_PATH=$(mktemp)
