Writing create-instances job
Description:
This is the create instances job.
It contains pretty much the same flow as in circle with the following changes:
- The paths of the files that needs to be used in later jobs is changed to the artifacts folder.
- `GCS_ARTIFACTS_KEY` and `GCS_ARTIFACTS_KEY` env variables now contains the **path** to the files containing the service account and not the content of the json file, this simplifies things when authenticating to GCP.
- `CIRCLE_BUILD_NUM` will. be replaced by `CI_BUILD_ID`
- `CIRCLE_WORKFLOW_ID` will be replaced by `CI_PIPELINE_ID`
- `CIRCLE_BRANCH` will be replaced by `CI_COMMIT_BRANCH`
- The `$CIRCLE_NODE_INDEX` does not exist in gitlab which brings up the question of whether to maintain the circle upload path: `content/$CIRCLE_BRANCH/$CIRCLE_BUILD_NUM/$CIRCLE_NODE_INDEX` (where CIRCLE_NODE_INDEX = 0) or just remove it (which could be a bit simpler but break BC) @glicht @guyfreund
- Since the build's image runs on python 3.9 which does not support Enum extension - a small fix for the sdk has been implemented as well [here](https://github.com/demisto/demisto-sdk/pull/1140).
Related issues:
fixes: https://github.com/demisto/etc/issues/35417

Build example:
https://code-stage.pan.run/xsoar/content/-/jobs/11263021

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,6 +9,11 @@ default:
       - venv/
       - node_modules/
     when: always
+  artifacts:
+    expire_in: 30 days
+    paths:
+      - /builds/xsoar/content/artifacts/*
+    when: always
   before_script:
     - echo "=== Running before script ==="
     - git checkout $CI_COMMIT_BRANCH
@@ -17,12 +22,12 @@ default:
       if [[ -f "$BASH_ENV" ]]; then
         source "$BASH_ENV"
       fi
+    - source .circleci/content_release_vars.sh
     - echo "=== Creating new clean logs folder ==="
     - rm -rf $ARTIFACTS_FOLDER/logs
     - mkdir -p $ARTIFACTS_FOLDER/logs
     - echo "=== Granting execute permissions on files ==="
     - chmod +x ./Tests/scripts/*
-    - chmod +x ./Tests/lastest_server_build_scripts/*
     - chmod +x ./Tests/Marketplace/*
     - echo "=== Installing Virtualenv ==="
     - |
@@ -63,9 +68,6 @@ default:
 
 
 variables:
-  CONTENT_VERSION: "21.3.2"
-  SERVER_VERSION: "6.0.0"
-  GIT_SHA1: "6fee942518c6b2275a6cb61c1824574171cf58f9" # guardrails-disable-line disable-secrets-detection
   DONT_CACHE_LAST_RESPONSE: "true"
   GCS_MARKET_BUCKET: "marketplace-dist"
   SLACK_CHANNEL: "dmst-content-team"
@@ -85,3 +87,77 @@ stages:
   - create-instances
   - run-instances
   - upload-to-marketplace
+
+create-instances:
+  stage: create-instances
+  script:
+    - |
+      demisto-sdk create-id-set -o ./Tests/id_set.json
+      cp ./Tests/id_set.json $ARTIFACTS_FOLDER
+    - python3 Utils/release_notes_generator.py $CONTENT_VERSION $CI_COMMIT_SHA $CI_BUILD_ID --output $ARTIFACTS_FOLDER/packs-release-notes.md --github-token $GITHUB_TOKEN
+    - ./Documentation/commonServerDocs.sh
+    -  demisto-sdk create-content-artifacts -a $ARTIFACTS_FOLDER --cpus 8 --content_version $CONTENT_VERSION
+    - gcloud auth activate-service-account --key-file="$GCS_ARTIFACTS_KEY"
+    - successful_feature_branch_build=$(gsutil ls "gs://xsoar-ci-artifacts/content/$FEATURE_BRANCH_NAME/*" | tail -n 1 | grep -o -E "content/$FEATURE_BRANCH_NAME/[0-9]*")
+    - echo $successful_feature_branch_build
+    - python3 Utils/merge_content_new_zip.py -f $FEATURE_BRANCH_NAME -b $successful_feature_branch_build
+    - zip -j $ARTIFACTS_FOLDER/uploadable_packs.zip $ARTIFACTS_FOLDER/uploadable_packs/* || ((($? > 0)) && echo "failed to zip the uploadable packs, ignoring the failure" && exit 0)
+    - rm -rf $ARTIFACTS_FOLDER/uploadable_packs
+    - python3 ./Tests/scripts/update_conf_json.py
+    - cp "./Tests/conf.json" "$ARTIFACTS_FOLDER/conf.json"
+    - |
+      if [ -n "${INSTANCE_TESTS}" ];
+        then
+          echo "Skipping - not running in INSTANCE_TESTS build"
+        else
+          echo "====== Collecting tests and content packs ======"
+          [ -n "${NIGHTLY}" ] && IS_NIGHTLY=true || IS_NIGHTLY=false
+          python3 ./Tests/scripts/collect_tests_and_content_packs.py -n $IS_NIGHTLY
+      fi
+    - python3 ./Tests/Marketplace/packs_dependencies.py -i ./Tests/id_set.json -o $ARTIFACTS_FOLDER/packs_dependencies.json
+    - |
+      if [[ -n "${CONTRIB_BRANCH}" || -n "${DEMISTO_SDK_NIGHTLY}" ]] ; then
+        echo "Skipping Preparing Content Packs For Testing since nightly instances uses production bucket"
+      else
+        echo "====== Preparing Content Packs For Testing ======"
+        ./Tests/scripts/prepare_content_packs_for_testing.sh "$GCS_MARKET_BUCKET"
+      fi
+    - |
+      if [[ -n "${DEMISTO_SDK_NIGHTLY}" ]] || [[ $CI_COMMIT_BRANCH != master ]] && [[ $CI_COMMIT_BRANCH != 20\.* ]] && [[ $CI_COMMIT_BRANCH != 21\.* ]]; then
+        echo "Skipping packs download to artifact on non master or release branch"
+      else
+        ZIP_FOLDER=$(mktemp -d)
+        python3 ./Tests/Marketplace/zip_packs.py -b 'marketplace-dist' -z $ZIP_FOLDER -a $ARTIFACTS_FOLDER -s $GCS_MARKET_KEY
+      fi
+    - |
+      if [ -n "${DEMISTO_SDK_NIGHTLY}" ];
+        then
+          echo "Skipping - not running in INSTANCE_TESTS build"
+        else
+          echo "====== Uploading artifacts to GCP ======"
+          ./Tests/scripts/upload_artifacts.sh
+      fi
+    - |
+      if [ -n "${DEMISTO_SDK_NIGHTLY}" ];
+        then
+          echo "Skipping - not running in INSTANCE_TESTS build"
+        else
+        echo "====== Creating instances ======"
+          [ -n "${TIME_TO_LIVE}" ] && TTL=${TIME_TO_LIVE} || TTL=300
+          if [ -n "${NIGHTLY}" ] ;
+            then
+              export IFRA_ENV_TYPE=Nightly # disable-secrets-detection
+          elif [ -n "${INSTANCE_TESTS}" ] ;
+            then
+              export IFRA_ENV_TYPE="Server 5.5" # disable-secrets-detection
+          elif [[ -n "${CONTRIB_BRANCH}" || -n "${DEMISTO_SDK_NIGHTLY}" ]] ;
+            then
+              export IFRA_ENV_TYPE="Server Master" # disable-secrets-detection
+          elif [ -n "${BUCKET_UPLOAD}" ] ;
+            then
+              export IFRA_ENV_TYPE="Bucket-Upload" # disable-secrets-detection
+          else
+            export IFRA_ENV_TYPE=Content-Env # disable-secrets-detection
+          fi
+          python3 ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType "$IFRA_ENV_TYPE" -timetolive $TTL -outfile "$ARTIFACTS_FOLDER/env_results.json"
+      fi
