get server artifact inline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,7 @@ jobs:
               sudo npm install -g jsdoc-to-markdown
               sudo pip install git+https://github.com/rahulrrixe/parinx.git@master
               sudo pip install awscli
+              chmod +x ./Tests/scripts/*
       - run:
           name: Validate Files and Yaml
           command: |
@@ -47,8 +48,34 @@ jobs:
       - run:
           name: Download Artifacts
           command: |
-              chmod +x ./Tests/scripts/*
-              ./Tests/scripts/server_get_artifact.sh $SERVER_CI_TOKEN
+              ACCEPT_TYPE="Accept: application/json"
+              SERVER_API_URI="https://circleci.com/api/v1/project/demisto/server"
+              TOKEN_ATTR="circle-token=$SERVER_CI_TOKEN"
+
+              echo "Getting latest build num"
+              TEMP=$(curl -s -H "$ACCEPT_TYPE" "$SERVER_API_URI/tree/master?limit=5&filter=successful&$TOKEN_ATTR")
+
+              ARTIFACT_BUILD_NUM=
+              for i in `seq 0 4`; do
+                  if [[ $(echo "$TEMP" | jq ".[$i].build_parameters") == "null" ]]; then
+                      ARTIFACT_BUILD_NUM=$(echo "$TEMP" | jq ".[$i].build_num")
+                      break
+                  fi
+              done
+
+              if [[ "$ARTIFACT_BUILD_NUM" = "" ]]; then
+                  echo "couldn't find successful build"
+                  exit 1
+              fi
+
+              SERVER_DOWNLOAD_LINK=$(curl -s -H "$ACCEPT_TYPE" ${SERVER_API_URI}/${ARTIFACT_BUILD_NUM}/artifacts?${TOKEN_ATTR} | jq '.[].url' -r | grep demistoserver | grep /0/)
+
+              echo "Getting server artifact for build: ${ARTIFACT_BUILD_NUM}"
+              echo "SERVER_DOWNLOAD_LINK = ${SERVER_DOWNLOAD_LINK}"
+
+              curl --silent -o demistoserver.sh ${SERVER_DOWNLOAD_LINK}?${TOKEN_ATTR}
+
+              echo "Done!"
       - run:
           name: Create Instance
           command: |
