fixup! TEMP

diff --git a/.hooks/bootstrap b/.hooks/bootstrap
--- a/.hooks/bootstrap
+++ b/.hooks/bootstrap
@@ -55,7 +55,7 @@ poetry check
 echo "Installing dependencies..."
 if [ -n "$CI" ]; then
     echo "Detected CI env. Running extra requiements"
-    poetry install --with ci --verbose
+    poetry install --with ci --verbose || echo "failed but ltes continue."
 else
     echo "Detected local env."
     poetry install
