bye bye py2

diff --git a/.hooks/bootstrap b/.hooks/bootstrap
--- a/.hooks/bootstrap
+++ b/.hooks/bootstrap
@@ -8,40 +8,17 @@ set -e
 #
 # This includes:
 # * install pre-commit hooks
-# * setup virtualenv
+# * setup content dependencies with poetry
+# * Setup npm
 
 if [ "$1" == "-h" -o "$1" == "--help" ]; then
     cat << EOF
 Setup development environment (run with no arguments):
 * install pre-commit hooks (set NO_HOOKS=1 to skip)
-* setup venv virtualenv (set NO_VENV=1 to skip)
-
-To update python packages run: $0 -u
 
 EOF
 exit 0
 fi
-
-# if [ "$1" == "-u" -o "$1" == "--update" ]; then
-#     if [ ! -f "venv/bin/pip2" -a ! -f "venv/bin/pip3" ]; then
-#         echo "ERROR: It seems that venv hasn't been setup. Run $0 to fully setup the venv without the [$1] option."
-#         exit 1
-#     fi
-#     if [ -f "venv/bin/pip2" ]; then
-#         echo "Updating python 2 dependencies ..."
-#         venv/bin/pip2 install -r dev-requirements-py2.txt
-#     fi
-#     if [ -f "venv/bin/pip3" ]; then
-#         echo "Updating python 3 dependencies ..."
-#         venv/bin/pip3 install -r dev-requirements-py3.txt -U --upgrade-strategy only-if-needed
-#     fi
-#     if [ -d "node_modules" ]; then
-#         echo "Updating node modules"
-#         npm install
-#     fi
-#     echo "Done updating dependencies"
-#     exit 0
-# fi
 
 if [ ! "$PWD" == "$(git rev-parse --show-toplevel)" ]; then
     cat >&2 <<__EOF__
@@ -67,50 +44,17 @@ fi
 
 echo "======================="
 
-if [ -n "$NO_VENV" ]; then
-    echo "Skipping venv setup as environment varialbe NO_VENV is set"
-else
-    if ! command -v poetry >/dev/null 2>&1; then
-        echo "ERROR: poetry is missing. Please install using: brew install poetry" 1>&2
-        exit 1
-    fi
-    SETUP_PY2=${SETUP_PY2:-auto}
-    if [ "$SETUP_PY2" == "auto" ]; then
-        # we only setup PY2 if our remote origin is pointing to the demisto content repo (not a fork)
-        if git remote get-url origin | grep -E 'github.com:demisto/content.git$' >/dev/null 2>&1; then
-            echo "Will setup python 2 venv as detected content repo as remote"
-            echo "If you wish to skip python 2 setup, set environment variable SETUP_PY2=no"
-            SETUP_PY2=yes
-        else
-            INCLUDE_PY2_NOTE=yes
-        fi
-    fi
-    if [ "$SETUP_PY2" == "yes" ]; then
-        if ! command -v python2 >/dev/null 2>&1; then
-            echo "ERROR: python2 is missing. Please make sure you have Python 2 installed on your system" 1>&2
-            exit 1
-        fi
-        if ! command -v virtualenv >/dev/null 2>&1; then
-            echo "ERROR: virtualenv is missing. Please install using: pip install virtualenv" 1>&2
-            exit 1
-        fi
-        virtualenv -p python2 venv-py2
-    fi
-    echo "Installing dependencies..."
-    if [ "$SETUP_PY2" == "yes" ]; then
-        venv-py2/bin/pip2 install -r dev-requirements-py2.txt
-    fi
-    poetry install
-    if [ "$INCLUDE_PY2_NOTE" == "yes" ]; then
-        echo "=========================="
-        echo "Note: python 2 is NOT setup. If you require python 2 for your scripts/integrations run this command again"
-        echo "with the environment variable set: SETUP_PY2=yes"
-    fi
-        echo "=========================="
-        echo "Done setting up virtualenv with poetry"
-        echo "Activate the venv by running: poetry shell"
-        echo "Deactivate by running: deactivate"
-    fi
+
+if ! command -v poetry >/dev/null 2>&1; then
+    echo "ERROR: poetry is missing. Please install using: brew install poetry" 1>&2
+    exit 1
+fi
+echo "Installing dependencies..."
+poetry install
+echo "=========================="
+echo "Done setting up virtualenv with poetry"
+echo "Activate the venv by running: poetry shell"
+echo "Deactivate by running: deactivate"
 
 
 echo "======================="
