Review002

diff --git a/.hooks/bootstrap b/.hooks/bootstrap
--- a/.hooks/bootstrap
+++ b/.hooks/bootstrap
@@ -76,12 +76,6 @@ else
             echo "ERROR: virtualenv is missing. Please install using: pip install virtualenv" 1>&2
             exit 1
         fi
-        VIRTUALENV_VERSION=$(virtualenv --version)
-        if [[ $VIRTUALENV_VERSION != *16.7.* && "${SETUP_PY2}^^" != "NO" ]]; then
-            echo "ERROR: You are using virtualenv version ${VIRTUALENV_VERSION}, Please install virtualenv version 16.7.7:
-            pip3 uninstall virtualenv && pip3 install virtualenv==16.7.7"
-            exit 1
-        fi
         SETUP_PY2=${SETUP_PY2:-auto}
         if [ "$SETUP_PY2" == "auto" ]; then
             # we only setup PY2 if our remote origin is pointing to the demisto content repo (not a fork)
@@ -93,6 +87,14 @@ else
                 INCLUDE_PY2_NOTE=yes
             fi
         fi
+
+        VIRTUALENV_VERSION=$(virtualenv --version)
+        if [[ $VIRTUALENV_VERSION != *16.7.* && "$SETUP_PY2" != "yes" ]]; then
+            echo "ERROR: You are using virtualenv version ${VIRTUALENV_VERSION}, Please install virtualenv version 16.7.7:
+            pip3 uninstall virtualenv && pip3 install virtualenv==16.7.7"
+            exit 1
+        fi
+
         PY3CMD="python3"
         if command -v python3.8 >/dev/null 2>&1; then
             PY3CMD="python3.8"
