collect errors

diff --git a/.github/workflows/mdx-validation.yml b/.github/workflows/mdx-validation.yml
--- a/.github/workflows/mdx-validation.yml
+++ b/.github/workflows/mdx-validation.yml
@@ -156,11 +156,10 @@ jobs:
             exit 0
           fi
           errors=()
-          node - << 'EOF'
+          for file in $READMES; do
+            node - "$file" << 'EOF'
           const { readFile } = require('fs-extra');
           const mdx = require('@mdx-js/mdx');
-          const files = process.argv.slice(1);
-          let failedFiles = [];
 
           async function parseMDX(file) {
               try {
@@ -168,19 +167,25 @@ jobs:
                   await mdx(contents);
               } catch (error) {
                   console.error(`MDX parse failure in ${file}: ` + error);
-                  failedFiles.push(file);
+                  process.exit(1);
               }
           }
 
-          (async () => {
-              await Promise.all(files.map(parseMDX));
-              if (failedFiles.length > 0) {
-                  console.error("\n===============================");
-                  console.error("The following README.md files failed MDX validation:");
-                  console.error("===============================\n");
-                  failedFiles.forEach(file => console.error("- " + file));
-                  console.error("\n===============================");
-                  process.exit(1);
-              }
-          })();
-          EOF $READMES
+          const file = process.argv[2];
+          parseMDX(file);
+          EOF
+            if [ $? -ne 0 ]; then
+              errors+=("$file")
+            fi
+          done
+          
+          if [ ${#errors[@]} -ne 0 ]; then
+            echo "\n==============================="
+            echo "The following README.md files failed MDX validation:"
+            echo "===============================\n"
+            for err in "${errors[@]}"; do
+              echo "- $err"
+            done
+            echo "\n==============================="
+            exit 1
+          fi
