test

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -2,6 +2,8 @@ name: pre-commit
 on: pull_request
 
 jobs:
+  
+
   pre-commit:
     runs-on: ubuntu-latest
     permissions:
@@ -34,11 +36,11 @@ jobs:
         key: ${{ runner.os }}-pre-commit
 
     - name: run pre-commit
-      continue-on-error: true
       run: poetry run demisto-sdk pre-commit -g --unit-test --validate --sdk-ref 04456f686b621fcb9cbbb5c224f37cf98624e1ac -v
 
     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3
+      if: always() # always run even if the previous step fails
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
@@ -50,6 +52,7 @@ jobs:
         annotate_only: true      
 
     - name: "Check coverage.xml exists"
+      if: always()
       id: check_files
       uses: andstor/file-existence-action@v2
       with:
@@ -57,7 +60,7 @@ jobs:
       
 
     - name: Code Coverage Report
-      if: steps.check_files.outputs.files_exists == 'true'
+      if: always() && steps.check_files.outputs.files_exists == 'true'
       uses: irongut/CodeCoverageSummary@v1.3.0
       with:
         filename: "coverage.xml"
@@ -69,8 +72,9 @@ jobs:
         
 
     - name: Append coverage to summary
+      if: always()
       id: append-coverage
-      run: |
-        if [[ -f code-coverage-results.md ]]; then
-          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY || echo "Missing coverage report"
-        fi
+        run: |
+          if [[ -f code-coverage-results.md ]]; then
+            cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY || echo "Missing coverage report"
+          fi
