try without env

diff --git a/.github/workflows/run-secrets-detection.yml b/.github/workflows/run-secrets-detection.yml
--- a/.github/workflows/run-secrets-detection.yml
+++ b/.github/workflows/run-secrets-detection.yml
@@ -34,7 +34,13 @@ jobs:
               echo "Error connecting to playbook: $investigation_return"
               exit 1
           fi
+          if [ -z INVESTIGATION_ID ];
+            then
+              echo "Error connecting to playbook: $investigation_return"
+              exit 1
+          fi
           echo ${{ env.INVESTIGATION_ID }}
+          echo ${{ INVESTIGATION_ID }}
       - name: Wait For Playbook To Finish
         env:
           GOLD_API_KEY: ${{ secrets.SECRETS_GOLD_API_KEY }}
