write investigation id to env

diff --git a/.github/workflows/run-secrets-detection.yml b/.github/workflows/run-secrets-detection.yml
--- a/.github/workflows/run-secrets-detection.yml
+++ b/.github/workflows/run-secrets-detection.yml
@@ -28,13 +28,18 @@ jobs:
           PASSWORD: ${{ secrets.SECRET_CHECK_PASS }}
         run: |
           echo "Run secrets detection for PR: $PR_NUMBER on branch: $BRANCH_NAME"
-          investigation_id=$(python Utils/github_workflow_scripts/run_secrets_detection.py --pr_number $PR_NUMBER --branch_name $BRANCH_NAME --username $USERNAME --password $PASSWORD)
-          echo "INVESTIGATION_ID=$investigation_id" >> $GITHUB_ENV
+          investigation_return=$(python Utils/github_workflow_scripts/run_secrets_detection.py --pr_number $PR_NUMBER --branch_name $BRANCH_NAME --username $USERNAME --password $PASSWORD)
+          if [ -z env.INVESTIGATION_ID ];
+            then
+              echo "Error connecting to playbook: $investigation_return"
+              exit 1
+          fi
+          echo ${{ env.INVESTIGATION_ID }}
       - name: Wait For Playbook To Finish
         env:
           GOLD_API_KEY: ${{ secrets.SECRETS_GOLD_API_KEY }}
         run: |
-          echo "Invastigation id is: $INVESTIGATION_ID "
-          python Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py -i $INVESTIGATION_ID -k $GOLD_API_KEY
+          echo "Invastigation id is: $env.INVESTIGATION_ID "
+          python Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py -i $env.INVESTIGATION_ID -k $GOLD_API_KEY
 
 
