Fixing the instance role not being created causing the slack notifier to fail (#31048)
Fixing the instance role not being created causing the slack notifier to fail #31048

diff --git a/.gitlab/ci/.gitlab-ci.global.yml b/.gitlab/ci/.gitlab-ci.global.yml
--- a/.gitlab/ci/.gitlab-ci.global.yml
+++ b/.gitlab/ci/.gitlab-ci.global.yml
@@ -289,6 +289,16 @@
   inherit: # see https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27775
     variables: false
 
+.destroy_xsoar_instances:
+  - section_start "Destroy Instances"
+  - python3 ./Tests/scripts/destroy_instances.py --artifacts-dir "${ARTIFACTS_FOLDER}" --env-file "${ENV_RESULTS_PATH}" --instance-role "${INSTANCE_ROLE}"
+  - destroy_instances_exit_code=$?
+  - |
+    if [ "${destroy_instances_exit_code}" -ne 0 ]; then
+      echo "Failed to destroy instances of role ${INSTANCE_ROLE}, exit code: ${destroy_instances_exit_code}"
+    fi
+  - section_end "Destroy Instances"
+
 .lock-machine:
   - section_start "Lock Machine" --collapsed
   - echo "Authenticating GCP"
