run unittesting even when bucket upload is against dev bucket

diff --git a/.gitlab/ci/global.yml b/.gitlab/ci/global.yml
--- a/.gitlab/ci/global.yml
+++ b/.gitlab/ci/global.yml
@@ -171,33 +171,33 @@
     - section_end "Test Infrustracture"
     - section_start "Run Unit Testing and Lint"
     - |
-      if [[ -n $FORCE_BUCKET_UPLOAD || -n $BUCKET_UPLOAD ]] && [[ "$(echo "$GCS_MARKET_BUCKET" | tr '[:upper:]' '[:lower:]')" != "marketplace-dist" ]]; then
-        echo "Skipping validations when uploading to a test bucket."
-      else
-        echo "demisto-sdk version: $(demisto-sdk --version)"
-        echo "mypy version: $(mypy --version)"
-        echo "flake8 py2 version: $(python2 -m flake8 --version)"
-        echo "flake8 py3 version: $(python3 -m flake8 --version)"
-        echo "bandit py2 version: $(python2 -m bandit --version 2>&1)"
-        echo "bandit py3 version: $(python3 -m bandit --version 2>&1)"
-        echo "vulture py2 version: $(python2 -m vulture --version 2>&1)"
-        echo "vulture py3 version: $(python3 -m vulture --version 2>&1)"
-        SHOULD_LINT_ALL=$(./Tests/scripts/should_lint_all.sh)
-        mkdir ./unit-tests
-        if [ -n "$SHOULD_LINT_ALL" ]; then
-          echo -e  "----------\nLinting all because:\n${SHOULD_LINT_ALL}\n----------"
-          if [[ -n "$PARALLEL" && -n "$CI_NODE_INDEX" ]]; then
-            mkdir -p "./unit-tests/$CI_NODE_INDEX" || true
-            mkdir -p "$ARTIFACTS_FOLDER/$CI_NODE_INDEX" || true
-            [ -n "${TESTING_UNIT_TESTING}" ] && dirs_to_test=$(cat "$ARTIFACTS_FOLDER/test_groups/test_dirs_$CI_NODE_INDEX.txt" | tail -n5 | tr '\n' ',' | sed -E 's/,$//') || dirs_to_test=$(cat "$ARTIFACTS_FOLDER/test_groups/test_dirs_$CI_NODE_INDEX.txt" | tr '\n' ',' | sed -E 's/,$//')
-            demisto-sdk lint -p 8 -q --test-xml "./unit-tests/$CI_NODE_INDEX" --log-path "$ARTIFACTS_FOLDER/$CI_NODE_INDEX" --failure-report "$ARTIFACTS_FOLDER/$CI_NODE_INDEX" -i "$dirs_to_test"
-          else
-            demisto-sdk lint -p 8 -a -q --test-xml ./unit-tests --log-path $ARTIFACTS_FOLDER --failure-report $ARTIFACTS_FOLDER
-          fi
+      # if [[ -n $FORCE_BUCKET_UPLOAD || -n $BUCKET_UPLOAD ]] && [[ "$(echo "$GCS_MARKET_BUCKET" | tr '[:upper:]' '[:lower:]')" != "marketplace-dist" ]]; then
+      #   echo "Skipping validations when uploading to a test bucket."
+      # else
+      echo "demisto-sdk version: $(demisto-sdk --version)"
+      echo "mypy version: $(mypy --version)"
+      echo "flake8 py2 version: $(python2 -m flake8 --version)"
+      echo "flake8 py3 version: $(python3 -m flake8 --version)"
+      echo "bandit py2 version: $(python2 -m bandit --version 2>&1)"
+      echo "bandit py3 version: $(python3 -m bandit --version 2>&1)"
+      echo "vulture py2 version: $(python2 -m vulture --version 2>&1)"
+      echo "vulture py3 version: $(python3 -m vulture --version 2>&1)"
+      SHOULD_LINT_ALL=$(./Tests/scripts/should_lint_all.sh)
+      mkdir ./unit-tests
+      if [ -n "$SHOULD_LINT_ALL" ]; then
+        echo -e  "----------\nLinting all because:\n${SHOULD_LINT_ALL}\n----------"
+        if [[ -n "$PARALLEL" && -n "$CI_NODE_INDEX" ]]; then
+          mkdir -p "./unit-tests/$CI_NODE_INDEX" || true
+          mkdir -p "$ARTIFACTS_FOLDER/$CI_NODE_INDEX" || true
+          [ -n "${TESTING_UNIT_TESTING}" ] && dirs_to_test=$(cat "$ARTIFACTS_FOLDER/test_groups/test_dirs_$CI_NODE_INDEX.txt" | tail -n5 | tr '\n' ',' | sed -E 's/,$//') || dirs_to_test=$(cat "$ARTIFACTS_FOLDER/test_groups/test_dirs_$CI_NODE_INDEX.txt" | tr '\n' ',' | sed -E 's/,$//')
+          demisto-sdk lint -p 8 -q --test-xml "./unit-tests/$CI_NODE_INDEX" --log-path "$ARTIFACTS_FOLDER/$CI_NODE_INDEX" --failure-report "$ARTIFACTS_FOLDER/$CI_NODE_INDEX" -i "$dirs_to_test"
         else
-          demisto-sdk lint -p 8 -g -v --test-xml ./unit-tests --log-path $ARTIFACTS_FOLDER --failure-report $ARTIFACTS_FOLDER --coverage-report $ARTIFACTS_FOLDER/coverage_report
+          demisto-sdk lint -p 8 -a -q --test-xml ./unit-tests --log-path $ARTIFACTS_FOLDER --failure-report $ARTIFACTS_FOLDER
         fi
+      else
+        demisto-sdk lint -p 8 -g -v --test-xml ./unit-tests --log-path $ARTIFACTS_FOLDER --failure-report $ARTIFACTS_FOLDER --coverage-report $ARTIFACTS_FOLDER/coverage_report
       fi
+      # fi
     - section_end "Run Unit Testing and Lint"
 
 .run-validations:
