use zip files

diff --git a/.gitlab/ci/on-push.yml b/.gitlab/ci/on-push.yml
--- a/.gitlab/ci/on-push.yml
+++ b/.gitlab/ci/on-push.yml
@@ -97,8 +97,9 @@ validate-content-conf:
 
     - |
       echo "Trying to pull all CSV import files from bucket"
-      # gcloud auth activate-service-account --key-file="$GCS_MARKET_KEY" > auth.out 2>&1
-      # gsutil -m cp -r "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*" /var/lib/neo4j/import || echo "failed to download graph imports."
+      gcloud auth activate-service-account --key-file="$GCS_MARKET_KEY" > auth.out 2>&1
+      gsutil -m cp "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/content_graph.zip" /var/lib/neo4j/import/content_graph.zip || echo "failed to download graph imports."
+      unzip -o /var/lib/neo4j/import/content_graph.zip -d /var/lib/neo4j/import
       echo "Successfully pulled all CSV import files from bucket"
     - |
       if [ -z "$(ls -A /var/lib/neo4j/import)" ]; then
@@ -118,8 +119,8 @@ validate-content-conf:
     - |
       echo "Moving exported CSV files to artifacts"
       mkdir $ARTIFACTS_FOLDER/content_graph
-      cp -R /var/lib/neo4j/import $ARTIFACTS_FOLDER/content_graph
-      zip -r $ARTIFACTS_FOLDER/content_graph/content_graph.zip $ARTIFACTS_FOLDER/content_graph/import/*
+      zip -r /var/lib/neo4j/import/content_graph.zip /var/lib/neo4j/import/*
+      cp /var/lib/neo4j/import/content_graph.zip $ARTIFACTS_FOLDER/content_graph
 
     - section_end "Update content graph"
 
