Test

diff --git a/.gitlab/ci/on-push.yml b/.gitlab/ci/on-push.yml
--- a/.gitlab/ci/on-push.yml
+++ b/.gitlab/ci/on-push.yml
@@ -39,12 +39,43 @@ run-unittests-and-lint:
 
 
 # runs in circle for the on-push flow (because we need to run it there for contributors anyways)
-run-validations:
+run-validations_nightly:
   extends:
     - .run-validations
   rules:
     - if: '$NIGHTLY'
 
+run-validations:
+  stage: unittests-and-validations
+  needs: []
+  extends:
+    - .default-job-settings
+  variables:
+    KUBERNETES_CPU_REQUEST: 1000m
+  artifacts:
+    expire_in: 30 days
+    paths:
+      - /builds/xsoar/content/artifacts/*
+    when: always
+  rules:
+    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/ && $CI_COMMIT_BRANCH !~ /^[0-9]{2}\.[0-9]{1,2}\.[0-9]$/'
+  script:
+    - section_start "Validate content-test-conf Branch Merged"
+    - |
+      if [[ $CI_COMMIT_BRANCH = "master" ]]; then
+        echo "Skipping, Should not run on master branch."
+      else
+        # replace slashes ('/') in the branch name, if exist, with underscores ('_')
+        UNDERSCORE_CI_BRANCH=${CI_COMMIT_BRANCH//\//_}
+        git clone --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@code.pan.run/xsoar/content-test-conf.git --branch $UNDERSCORE_CI_BRANCH
+        if [ "$?" != "0" ]; then
+          echo "No such branch in content-test-conf: $UNDERSCORE_CI_BRANCH"
+        else
+          echo "ERROR: Found a branch with the same name in contest-test-conf conf.json - $UNDERSCORE_CI_BRANCH.\n Merge it in order to merge the current branch into content repo."
+          exit 1
+        fi
+      fi
+    - section_end "Validate content-test-conf Branch Merged"
 
 create-instances:
   tags:
