test upload trigger

diff --git a/.gitlab/ci/on-push.yml b/.gitlab/ci/on-push.yml
--- a/.gitlab/ci/on-push.yml
+++ b/.gitlab/ci/on-push.yml
@@ -98,7 +98,7 @@ validate-content-conf:
     - |
       echo "Trying to pull all CSV import files from bucket"
       gcloud auth activate-service-account --key-file="$GCS_MARKET_KEY" > auth.out 2>&1
-      # gsutil -m cp -r "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*" /var/lib/neo4j/import || echo "failed to download graph imports."
+      gsutil -m cp -r "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*" /var/lib/neo4j/import || echo "failed to download graph imports."
       echo "Successfully pulled all CSV import files from bucket"
     - |
       if [ -z "$(ls -A /var/lib/neo4j/import)" ]; then
@@ -174,10 +174,10 @@ validate-content-conf:
     - section_end "Create Instances for XSOAR"
     
     - |
-      if [[ $BUCKET_UPLOAD == "true" ]]; then
+      if [[ $BUCKET_UPLOAD == "true" && $TEST_UPLOAD == "false" ]]; then
         section_start "Upload CSV to bucket" --collapsed
         # delete command after decide how to upload in prod
-        # gsutil -m cp -r /var/lib/neo4j/import/* "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*"
+        gsutil -m cp -r /var/lib/neo4j/import/* "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*"
         section_end "Upload Artifacts to GCP"
       fi
     
