Delete id_set from content build and upload-flow (#22517)
]

diff --git a/.gitlab/ci/on-push.yml b/.gitlab/ci/on-push.yml
--- a/.gitlab/ci/on-push.yml
+++ b/.gitlab/ci/on-push.yml
@@ -22,7 +22,6 @@ trigger-private-build:
     - python3 Utils/get_private_build_status.py --github-token $GITHUB_TOKEN
   timeout: 2 hours
 
-
 .create-release-notes-and-common-docs:
   - section_start "Create Release Notes and Common Server Documentation" --collapsed
   - echo "Creating Release Notes and Content Descriptor"
@@ -76,183 +75,144 @@ validate-content-conf:
       fi
     - section_end "Validate content-tesgt-conf Branch Merged"
 
-create-instances:
+.generic-prepare-testing-bucket:
   tags:
     - gke
   extends:
     - .default-job-settings
   rules:
-    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/'
-    - if: '$NIGHTLY'
-    - if: '$INSTANCE_TESTS'
+    - if: "$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/"
+    - if: "$NIGHTLY"
   cache:
     policy: pull-push
   variables:
-    ARTIFACTS_FOLDER: "${ARTIFACTS_FOLDER_XSOAR}"
     KUBERNETES_CPU_REQUEST: 2000m
   needs: []
-  stage: create-instances
+  stage: prepare-testing-bucket
   script:
     - !reference [.download-demisto-conf]
-    - !reference [.create-id-set-xsoar]
     - !reference [.create-release-notes-and-common-docs]
 
+    - section_start "Create or update content graph" --collapsed
+
+    - |
+      echo "Trying to pull all CSV import files from bucket"
+      gcloud auth activate-service-account --key-file="$GCS_MARKET_KEY" > auth.out 2>&1
+      gsutil -m cp -r "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*" /var/lib/neo4j/import || echo "failed to download graph imports."
+      echo "Successfully pulled all CSV import files from bucket"
+    - |
+      if [ -z "$(ls -A /var/lib/neo4j/import)" ]; then
+        echo "No CSV files to import, creating the content graph"
+        demisto-sdk create-content-graph
+        echo "Successfully created content graph"
+      else
+        echo "Getting the list of packs to update in content graph"
+        PACKS_TO_UPDATE=( $(git diff $LAST_UPLOAD_COMMIT --name-only -- Packs/* | awk -F/ '{print $2}' | sort | uniq) )
+        echo "Updating graph for packs: $PACKS_TO_UPDATE"
+
+        echo "Updating the content graph"
+        demisto-sdk update-content-graph -p $PACKS_TO_UPDATE
+        echo "Successfully updated content graph"
+      fi
+
+    - |
+      echo "Moving exported CSV files to artifacts"
+      mkdir $ARTIFACTS_FOLDER/content_graph
+      cp -R /var/lib/neo4j/import $ARTIFACTS_FOLDER/content_graph
+
+    - section_end "Update content graph"
+
     - section_start "Create Content Artifacts and Update Conf" --collapsed
-    - demisto-sdk create-content-artifacts -a $ARTIFACTS_FOLDER --cpus 8 --content_version $CONTENT_VERSION --marketplace "xsoar" -fbi -idp ./Tests/id_set.json >> $ARTIFACTS_FOLDER/logs/create_content_artifacts.log
+    - |
+      if [[ $MARKETPLACE_VERSION == "xsoar" ]];
+      then
+        echo "Starting to create artifacts with zip for XSOAR."
+        python Tests/scripts/create_artifacts_graph/create_artifacts.py --marketplace "xsoar" --artifacts-output $ARTIFACTS_FOLDER/content_packs --dependencies-output $ARTIFACTS_FOLDER/packs_dependencies.json
+      else
+        echo "Starting to create artifacts without zip."
+        python Tests/scripts/create_artifacts_graph/create_artifacts.py --marketplace "$MARKETPLACE_VERSION" --artifacts-output $ARTIFACTS_FOLDER/content_packs --dependencies-output $ARTIFACTS_FOLDER/packs_dependencies.json --no-zip
+      fi
+
     - gcloud auth activate-service-account --key-file="$GCS_ARTIFACTS_KEY"
-    - successful_feature_branch_build=$(gsutil ls "gs://xsoar-ci-artifacts/content/$FEATURE_BRANCH_NAME/*" | tail -n 1 | grep -o -E "content/$FEATURE_BRANCH_NAME/[0-9]*")
-    - echo $successful_feature_branch_build
-    - python3 Utils/merge_content_new_zip.py -f $FEATURE_BRANCH_NAME -b $successful_feature_branch_build
-    - zip -j $ARTIFACTS_FOLDER/uploadable_packs.zip $ARTIFACTS_FOLDER/uploadable_packs/* >> $ARTIFACTS_FOLDER/logs/zipping_uploadable_packs.log || echo "failed to zip the uploadable packs, ignoring the failure"
-    - rm -rf $ARTIFACTS_FOLDER/uploadable_packs
+
     - cp "./Tests/conf.json" "$ARTIFACTS_FOLDER/conf.json"
     - section_end "Create Content Artifacts and Update Conf"
 
-    - section_start "Collect Tests"
+    - section_start "Replace Cortex XSOAR" --collapsed
+    - |
+      if [[ $MARKETPLACE_VERSION != "xsoar" ]];
+      then
+        echo "Replace Cortex XSOAR for non-xsoar build."
+        pushd "$ARTIFACTS_FOLDER"
+        find content_packs -type f -not \( -path "*/ReleaseNotes/*" \) -exec sed -i -e 's/Cortex XSOAR/'"$PRODUCTNAME"'/gI' {} \;
+        pushd content_packs; zip -r ../content_packs.zip * 1> /dev/null; popd
+        rm -rf content_packs
+        popd
+      fi
+    - section_end "Replace Cortex XSOAR"
+    - section_start "Collect Tests" --collapsed
     - |
       if [ -n "${INSTANCE_TESTS}" ]; then
         echo "Skipping - not running in INSTANCE_TESTS build"
       else
         [ -n "${NIGHTLY}" ] && IS_NIGHTLY=true || IS_NIGHTLY=false
-        python3 ./Tests/scripts/collect_tests/collect_tests.py -n $IS_NIGHTLY --marketplace "xsoar" --service_account $GCS_MARKET_KEY
+        python3 ./Tests/scripts/collect_tests/collect_tests.py -n $IS_NIGHTLY --marketplace "$MARKETPLACE_VERSION" --service_account $GCS_MARKET_KEY --graph true
       fi
     - section_end "Collect Tests"
-    
-    - section_start "Calculate Packs Dependencies" --collapsed
-    - demisto-sdk find-dependencies -idp ./Tests/id_set.json --output-path $ARTIFACTS_FOLDER/packs_dependencies.json --all-packs-dependencies
-    - section_end "Calculate Packs Dependencies"
 
     - section_start "Prepare Content Packs for Testing"
-    - ./Tests/scripts/prepare_content_packs_for_testing.sh "$GCS_MARKET_BUCKET" "$STORAGE_BASE_PATH"
+    - ./Tests/scripts/prepare_content_packs_for_testing.sh "$MARKETPLACE_BUCKET" "$STORAGE_BASE_PATH" "$MARKETPLACE_VERSION"
     - section_end "Prepare Content Packs for Testing"
 
-    - section_start "Create Instances"
+    - section_start "Create Instances for XSOAR"
     - |
-      [ -n "${TIME_TO_LIVE}" ] && TTL=${TIME_TO_LIVE} || TTL=300
-      python3 ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType "$IFRA_ENV_TYPE" -timetolive $TTL -outfile "$ARTIFACTS_FOLDER/env_results.json"
-    - section_end "Create Instances"
-
+      if [[ ${MARKETPLACE_VERSION} = "xsoar" ]]; then
+        echo "Creating Instances, only for XSOAR."
+        [ -n "${TIME_TO_LIVE}" ] && TTL=${TIME_TO_LIVE} || TTL=300
+        python3 ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType "$IFRA_ENV_TYPE" -timetolive $TTL -outfile "$ARTIFACTS_FOLDER/env_results.json"
+      fi
+    - section_end "Create Instances for XSOAR"
+    
+    - |
+      if [[ $BUCKET_UPLOAD == "true" && $TEST_UPLOAD == "false" ]]; then
+        section_start "Upload CSV to bucket" --collapsed
+        # delete command after decide how to upload in prod
+        gsutil -m cp -r /var/lib/neo4j/import/* "gs://$GCS_MARKET_BUCKET_DEV/content_graph/$MARKETPLACE_VERSION/*"
+        section_end "Upload Artifacts to GCP"
+      fi
+    
     - section_start "Upload Artifacts to GCP" --collapsed
     - ./Tests/scripts/upload_artifacts.sh
     - section_end "Upload Artifacts to GCP"
     - echo "create instances done" > "$ARTIFACTS_FOLDER/create_instances_done.txt"
 
-prepare-testing-bucket-mpv2:
-  tags:
-    - gke
-  extends:
-    - .default-job-settings
-  rules:
-    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/'
-    - if: '$NIGHTLY'
-  cache:
-    policy: pull-push
+
+
+xsoar-prepare-testing-bucket:
   variables:
-    ARTIFACTS_FOLDER: "${ARTIFACTS_FOLDER_MPV2}"
-    KUBERNETES_CPU_REQUEST: 2000m
-  needs: []
-  stage: create-instances
-  script:
-    - !reference [.download-demisto-conf]
-    - !reference [.create-id-set-mp-v2]
-    - !reference [.create-release-notes-and-common-docs]
-
-    - section_start "Create Content Artifacts and Update Conf" --collapsed
-    - demisto-sdk create-content-artifacts -a $ARTIFACTS_FOLDER --cpus 8 --content_version $CONTENT_VERSION --marketplace "marketplacev2" --no-zip -fbi -idp ./Tests/id_set.json >> $ARTIFACTS_FOLDER/logs/create_content_artifacts.log
-    - zip -j $ARTIFACTS_FOLDER/uploadable_packs_mpv2.zip $ARTIFACTS_FOLDER/uploadable_packs/* >> $ARTIFACTS_FOLDER/logs/zipping_uploadable_packs.log || echo "failed to zip the uploadable packs, ignoring the failure"
-    - rm -rf $ARTIFACTS_FOLDER/uploadable_packs
-    - cp "./Tests/conf.json" "$ARTIFACTS_FOLDER/conf.json"
-    - section_end "Create Content Artifacts and Update Conf"
-
-    - section_start "Calculate Packs Dependencies" --collapsed
-    - demisto-sdk find-dependencies -idp Tests/id_set.json --all-packs-dependencies -o $ARTIFACTS_FOLDER/packs_dependencies.json
-    - section_end "Calculate Packs Dependencies"
-
-    - section_start "Replace Cortex XSOAR" --collapsed
-    - pushd "$ARTIFACTS_FOLDER"
-    - find content_packs -type f -not \( -path "*/ReleaseNotes/*" \) -exec sed -i -e 's/Cortex XSOAR/'"$PRODUCT_NAME"'/gI' {} \;
-    - pushd content_packs; zip -r ../content_packs.zip *; popd
-    - pushd all_content; zip -r ../all_content.zip *; popd
-    - pushd content_new; zip -r ../content_new.zip *; popd
-    - pushd content_test; zip -r ../content_test.zip *; popd
-    - rm -rf content_packs all_content content_new content_test
-    - popd
-    - section_end "Replace Cortex XSOAR"
-
-    - section_start "Collect Tests and Content Packs"
-    - |
-      [ -n "${NIGHTLY}" ] && IS_NIGHTLY=true || IS_NIGHTLY=false
-      python3 ./Tests/scripts/collect_tests/collect_tests.py -n $IS_NIGHTLY --marketplace "marketplacev2" --service_account $GCS_MARKET_KEY
-    - section_end "Collect Tests and Content Packs"
-    
-    - section_start "Prepare Content Packs for Testing"
-    - ./Tests/scripts/prepare_content_packs_for_testing.sh "$GCS_MARKET_V2_BUCKET" "$STORAGE_BASE_PATH" "marketplacev2"
-    - section_end "Prepare Content Packs for Testing"
-
-    - section_start "Upload Artifacts to GCP" --collapsed
-    - ./Tests/scripts/upload_artifacts.sh
-    - section_end "Upload Artifacts to GCP"
-    - echo "create instances done" > "$ARTIFACTS_FOLDER/create_instances_done.txt"
-
-
-prepare-testing-bucket-xpanse:
-  tags:
-    - gke
+    ARTIFACTS_FOLDER: "${ARTIFACTS_FOLDER_XSOAR}"
+    MARKETPLACE_VERSION: "xsoar"
+    MARKETPLACE_BUCKET: "$GCS_MARKET_BUCKET"
   extends:
-    - .default-job-settings
-  rules:
-    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/'
-    - if: '$NIGHTLY'
-  cache:
-    policy: pull-push
+    - .generic-prepare-testing-bucket
+
+xpanse-prepare-testing-bucket:
   variables:
     ARTIFACTS_FOLDER: "${ARTIFACTS_FOLDER_XPANSE}"
-    KUBERNETES_CPU_REQUEST: 2000m
-  needs: []
-  stage: create-instances
-  script:
-    - !reference [.download-demisto-conf]
-    - !reference [.create-id-set-xpanse]
-    - !reference [.create-release-notes-and-common-docs]
+    MARKETPLACE_VERSION: "xpanse"
+    PRODUCTNAME: "Cortex XPANSE"
+    MARKETPLACE_BUCKET: "$GCS_MARKET_XPANSE_BUCKET"
+  extends:
+    - .generic-prepare-testing-bucket
 
-    - section_start "Create Content Artifacts and Update Conf" --collapsed
-    - demisto-sdk create-content-artifacts -a $ARTIFACTS_FOLDER --cpus 8 --content_version $CONTENT_VERSION --marketplace "xpanse" --no-zip -fbi -idp ./Tests/id_set.json >> $ARTIFACTS_FOLDER/logs/create_content_artifacts.log
-    - zip -j $ARTIFACTS_FOLDER/uploadable_packs_xpanse.zip $ARTIFACTS_FOLDER/uploadable_packs/* >> $ARTIFACTS_FOLDER/logs/zipping_uploadable_packs.log || echo "failed to zip the uploadable packs, ignoring the failure"
-    - rm -rf $ARTIFACTS_FOLDER/uploadable_packs
-    - cp "./Tests/conf.json" "$ARTIFACTS_FOLDER/conf.json"
-    - section_end "Create Content Artifacts and Update Conf"
-
-    - section_start "Calculate Packs Dependencies" --collapsed
-    - demisto-sdk find-dependencies -idp Tests/id_set.json --all-packs-dependencies -o $ARTIFACTS_FOLDER/packs_dependencies.json
-    - section_end "Calculate Packs Dependencies"
-
-    - section_start "Replace Cortex XSOAR" --collapsed
-    - pushd "$ARTIFACTS_FOLDER"
-    - export PRODUCT_NAME_XPANSE="Cortex XPANSE"
-    - find content_packs -type f -not \( -path "*/ReleaseNotes/*" \) -exec sed -i -e 's/Cortex XSOAR/'"$PRODUCT_NAME_XPANSE"'/gI' {} \;
-    - pushd content_packs; zip -r ../content_packs.zip *; popd
-    - pushd all_content; zip -r ../all_content.zip *; popd
-    - pushd content_new; zip -r ../content_new.zip *; popd
-    - pushd content_test; zip -r ../content_test.zip *; popd
-    - rm -rf content_packs all_content content_new content_test
-    - popd
-    - section_end "Replace Cortex XSOAR"
-
-    - section_start "Collect Tests and Content Packs"
-    - |
-      [ -n "${NIGHTLY}" ] && IS_NIGHTLY=true || IS_NIGHTLY=false
-      python3 ./Tests/scripts/collect_tests/collect_tests.py -n $IS_NIGHTLY --marketplace "xpanse" --service_account $GCS_MARKET_KEY
-    - section_end "Collect Tests and Content Packs"
-
-    - section_start "Prepare Content Packs for Testing"
-    - ./Tests/scripts/prepare_content_packs_for_testing.sh "$GCS_MARKET_XPANSE_BUCKET" "$STORAGE_BASE_PATH" "xpanse"
-    - section_end "Prepare Content Packs for Testing"
-
-    - section_start "Upload Artifacts to GCP" --collapsed
-    - ./Tests/scripts/upload_artifacts.sh
-    - section_end "Upload Artifacts to GCP"
-    - echo "create instances done" > "$ARTIFACTS_FOLDER/create_instances_done.txt"
-
+mpv2-prepare-testing-bucket:
+  variables:
+    ARTIFACTS_FOLDER: "${ARTIFACTS_FOLDER_MPV2}"
+    MARKETPLACE_VERSION: "marketplacev2"
+    MARKETPLACE_BUCKET: "$GCS_MARKET_V2_BUCKET"
+    PRODUCTNAME: "Cortex XSIAM"
+  extends:
+    - .generic-prepare-testing-bucket
 
 .test_content_on_xsoar_server_instances_base:
   tags:
@@ -264,14 +224,14 @@ prepare-testing-bucket-xpanse:
     ARTIFACTS_FOLDER: "${ARTIFACTS_FOLDER_XSOAR}"
     ENV_RESULTS_PATH: "${ARTIFACTS_FOLDER_XSOAR}/env_results.json"
     SERVER_TYPE: "XSOAR"
-  needs: ["create-instances"]
   stage: run-instances
+  needs: ["xsoar-prepare-testing-bucket"]
   script:
     - '[[ "create instances done" = $(cat "$ARTIFACTS_FOLDER/create_instances_done.txt" 2> /dev/null) ]] || (echo "this is a known issue with GitLab pipline please mention @esharf in your PR" && exit 1)'
     - EXIT_CODE=0
     - !reference [.download-demisto-conf]
     - export TEMP=$(cat $ARTIFACTS_FOLDER/filter_envs.json | jq ".\"$INSTANCE_ROLE\"")
-# If instance was not created
+    # If instance was not created
     - |
       if [[ "$TEMP" != "true" && -z "${NIGHTLY}" ]]; then
         echo "Instance with role $INSTANCE_ROLE was not created"
@@ -310,7 +270,6 @@ prepare-testing-bucket-xpanse:
       python3 ./Tests/scripts/destroy_instances.py $ARTIFACTS_FOLDER $ARTIFACTS_FOLDER/env_results.json "$INSTANCE_ROLE" "$TIME_TO_LIVE" || EXIT_CODE=$?
     - exit $EXIT_CODE
 
-
 xsoar_server_6_5:
   extends: .test_content_on_xsoar_server_instances_base
   #  No need to trigger in case of release branch
@@ -318,7 +277,6 @@ xsoar_server_6_5:
     - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/ && $CI_COMMIT_BRANCH !~ /^[0-9]{2}\.[0-9]{1,2}\.[0-9]$/'
   variables:
     INSTANCE_ROLE: "Server 6.5"
-
 
 xsoar_server_6_6:
   extends: .test_content_on_xsoar_server_instances_base
@@ -387,7 +345,7 @@ slack-notify-nightly-build:
     GCS_MARKET_BUCKET: "${GCS_MARKET_V2_BUCKET}"
     ENV_RESULTS_PATH: "${ARTIFACTS_FOLDER_MPV2}/env_results.json"
     SERVER_TYPE: "XSIAM"
-  needs: ["prepare-testing-bucket-mpv2"]
+  needs: ["mpv2-prepare-testing-bucket"]
   stage: run-instances
   script:
     - '[[ "create instances done" = $(cat "$ARTIFACTS_FOLDER/create_instances_done.txt" 2> /dev/null) ]] || (echo "this is a known issue with GitLab pipline please mention @esharf in your PR" && exit 1)'
