Test

diff --git a/.gitlab/ci/on-push.yml b/.gitlab/ci/on-push.yml
--- a/.gitlab/ci/on-push.yml
+++ b/.gitlab/ci/on-push.yml
@@ -45,6 +45,27 @@ run-validations:
   rules:
     - if: '$NIGHTLY'
 
+validations:
+  stage: unittests-and-validations
+  rules:
+    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/ && $CI_COMMIT_BRANCH !~ /^[0-9]{2}\.[0-9]{1,2}\.[0-9]$/'
+  script:
+    - section_start "Validate content-test-conf Branch Merged"
+    - |
+      if [[ $CI_COMMIT_BRANCH = "master" ]]; then
+        echo "Skipping, Should not run on master branch."
+      else
+        # replace slashes ('/') in the branch name, if exist, with underscores ('_')
+        UNDERSCORE_CI_BRANCH=${CI_COMMIT_BRANCH//\//_}
+          if [ "$?" != "0" ]; then
+            echo "No such branch in content-test-conf: $UNDERSCORE_CI_BRANCH"
+          else
+            echo "ERROR: Found a branch with the same name in contest-test-conf conf.json - $UNDERSCORE_CI_BRANCH.\n Merge it in order to merge the current branch into content repo."
+            exit 1
+          fi
+        }
+      fi
+    - section_end "Validate content-test-conf Branch Merged"
 
 create-instances:
   tags:
